[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"

[project]
name = "Leafeon"
version = "0.0.0"
description = "A brief description of what your project does."
authors = [{ name = "Your Name", email = "youremail@example.com" }]
license = "MIT"
requires-python = ">=3.8"

# Correctly formatted dependencies section
dependencies = [
    "flask ^1.1.2",
    "requests ^2.25.1",
    # Add other runtime dependencies here
]

# Define development dependencies in optional-dependencies
optional-dependencies = {
    "dev" = [
        "pytest>=6.0,<7",
        "black==20.8b1",
        "flake8>=3.8,<4"
    ]
}

[tool.pdm]
python_requires = ">=3.8"  # Ensure PDM is aware of the Python version requirement
