version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.18.2  # Use Node.js image for building React app
    
    environment:
      CI: "false"

    steps:
      - checkout  # Checkout the source code
      - run:
          name: Navigate to frontend folder
          command: cd source/frontend  # Move to frontend folder

      - run:
          name: Install dependencies
          command: npm install --force # Install dependencies
          working_directory: source/frontend

      - run:
          name: Build
          command: npm run build  # Build the React application
          working_directory: source/frontend

      - run:
          name: Upload to S3
          command: |
            aws configure set aws_access_key_id $ACCESS_KEY
            aws configure set aws_secret_access_key $SECRET_KEY
            aws s3 sync build/ s3://leafeon  # Upload build artifacts to S3
